# This is a basic workflow to help you get started with Actions

name: Unit tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v1

    - name: Run npm install 
      run: npm install
      
    - name: Run Jest unit tests
      run: npm test
